const APP_VERSION = '1.0.0';
const BUILD = 1;
const KEY = 'francais-avec-luc:learner:v1';
const ITEMS = [
  { id:'bonjour', fr:'Bonjour', vi:'Xin chào' },
  { id:'merci', fr:'Merci', vi:'Cảm ơn' },
  { id:'au-revoir', fr:'Au revoir', vi:'Tạm biệt' },
  { id:'je-mappelle', fr:"Je m'appelle Trân.", vi:'Tôi tên là Trân.' },
];
const LESSON_STEPS = [
  {title:'Chào mừng, Trân',body:'Mình là Luc. Chúng ta sẽ học tiếng Pháp thật chậm, từ con số 0. Hôm nay chỉ có vài từ rất hữu ích — không cần học quá nhiều một lúc.'},
  {title:'Từ đầu tiên',french:'Bonjour',meaning:'Xin chào',body:'Đây là cách chào phổ biến và lịch sự trong tiếng Pháp. Nhấn nút nghe, rồi đọc theo nếu bạn muốn.',speak:'Bonjour'},
  {title:'Nhận biết',question:'“Bonjour” nghĩa là gì?',options:['Cảm ơn','Xin chào','Tạm biệt'],answer:'Xin chào'},
  {title:'Từ thứ hai',french:'Merci',meaning:'Cảm ơn',body:'Một từ rất quan trọng. Bạn sẽ dùng nó mỗi ngày.',speak:'Merci'},
  {title:'Tình huống nhỏ',question:'Ai đó đưa bạn một ly nước. Bạn nói gì?',options:['Merci','Bonjour','Au revoir'],answer:'Merci'},
  {title:'Khi rời đi',french:'Au revoir',meaning:'Tạm biệt',body:'Dùng khi bạn rời đi hoặc kết thúc một cuộc gặp.',speak:'Au revoir'},
  {title:'Giới thiệu tên',french:"Je m'appelle Trân.",meaning:'Tôi tên là Trân.',body:'Tạm thời hãy học cả cụm như một khối. Chưa cần phân tích ngữ pháp.',speak:"Je m'appelle Trân."},
  {title:'Tình huống cuối',question:'Bạn gặp Luc lần đầu. Chọn câu phù hợp nhất để bắt đầu.',options:["Bonjour. Je m'appelle Trân.",'Merci. Au revoir.','Au revoir. Merci.'],answer:"Bonjour. Je m'appelle Trân."},
  {title:'Xong Bài 1',body:'Hôm nay bạn đã học 4 điều đầu tiên: Bonjour, Merci, Au revoir và Je m’appelle Trân. Ngày mai, chúng ta sẽ dùng lại chúng trước khi học thêm.'},
];
const initialState = () => ({schemaVersion:1,learnerName:'Trân',level:'A0',lesson1Step:0,lesson1Completed:false,knownItems:[],reviewState:{},conversationWins:0,lastActivity:null,streak:{current:0,lastDate:null}});
let state = loadState();
let screen = 'home';
let lessonChoice = null;
let lessonFeedback = '';
let reviewIndex = 0;
let reviewRevealed = false;
let conversationRound = 0;
let conversationReply = '';

function loadState(){try{const raw=localStorage.getItem(KEY);if(!raw)return initialState();const parsed=JSON.parse(raw);return parsed.schemaVersion===1?{...initialState(),...parsed}:initialState()}catch{return initialState()}}
function saveState(next){const date=new Date().toISOString().slice(0,10);let streak=next.streak;if(streak.lastDate!==date){const y=new Date();y.setDate(y.getDate()-1);const yd=y.toISOString().slice(0,10);streak={current:streak.lastDate===yd?streak.current+1:1,lastDate:date}}state={...next,lastActivity:new Date().toISOString(),streak};localStorage.setItem(KEY,JSON.stringify(state))}
function patch(updater){saveState(typeof updater==='function'?updater(state):{...state,...updater});render()}
function h(value=''){return String(value).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function luc(small=false){return `<div class="luc ${small?'small':''}"><span>L</span></div>`}
function top(title,{back=false,settings=false}={}){return `<header class="topbar"><button class="icon-btn ${back?'':'invisible'}" data-go="home" aria-label="Quay lại">‹</button><div><div class="eyebrow">FRANÇAIS AVEC LUC</div><h1>${h(title)}</h1></div><button class="icon-btn ${settings?'':'invisible'}" data-go="settings" aria-label="Cài đặt">⚙</button></header>`}
function nav(){const buttons=[['home','⌂','Trang chủ'],['conversation','◌','Hội thoại'],['review','↻','Ôn tập'],['progress','✦','Tiến độ']];return `<nav class="bottom-nav">${buttons.map(([id,g,l])=>`<button data-go="${id}" class="${screen===id?'active':''}"><b>${g}</b><span>${l}</span></button>`).join('')}</nav>`}
function shell(content){return `<div class="app-shell"><main class="content">${content}</main>${nav()}</div>`}
function home(){const learned=state.knownItems.length;const pct=Math.round((state.lesson1Step/(LESSON_STEPS.length-1))*100);return `${top('Xin chào Trân 👋',{settings:true})}<section class="hero card"><div class="luc-row">${luc()}<div><span class="muted">Luc • gia sư của bạn</span><h2>Hôm nay mình học thật nhẹ nhàng.</h2></div></div><p>Chỉ vài phút. Một ít tiếng Pháp, giải thích chủ yếu bằng tiếng Việt.</p></section><section class="stats"><div class="stat"><span>A0</span><small>Trình độ</small></div><div class="stat"><span>${learned}</span><small>Đã học</small></div><div class="stat"><span>🔥 ${state.streak.current}</span><small>Ngày liên tiếp</small></div></section><section class="lesson-card card"><div class="row between"><span class="pill">Bài hôm nay</span><span class="muted">${pct}%</span></div><h2>Bài 1 — <em>Bonjour</em></h2><p>4 điều đầu tiên để chào hỏi và giới thiệu tên.</p><div class="progressbar"><span style="width:${Math.max(6,pct)}%"></span></div><button class="primary" data-go="lesson"><span class="glyph">▤</span>${state.lesson1Completed?'Xem lại bài học':state.lesson1Step?'Tiếp tục bài học':'Bắt đầu bài học'}<span>›</span></button></section><section class="grid-actions"><button class="action-card" data-go="conversation"><span class="glyph">◌</span><strong>Luyện hội thoại</strong><span>Tập dùng câu đã học</span></button><button class="action-card" data-go="review"><span class="glyph">↻</span><strong>Ôn tập</strong><span>Nhớ lâu hơn</span></button><button class="action-card" data-go="progress"><span class="glyph">✦</span><strong>Tiến độ</strong><span>Xem những gì đã học</span></button></section>`}
function lesson(){const i=Math.min(state.lesson1Step,LESSON_STEPS.length-1);const s=LESSON_STEPS[i];const can=!s.question||lessonFeedback.startsWith('Đúng');return `${top('Bài 1 — Bonjour',{back:true})}<div class="lesson-progress"><span style="width:${((i+1)/LESSON_STEPS.length)*100}%"></span></div><section class="teacher-line">${luc(true)}<div><strong>Luc</strong><span>Bước ${i+1}/${LESSON_STEPS.length}</span></div></section><section class="card lesson-step"><h2>${h(s.title)}</h2>${s.body?`<p>${h(s.body)}</p>`:''}${s.french?`<div class="french-block"><span class="fr">${h(s.french)}</span><span class="vi">${h(s.meaning)}</span><button class="listen" data-speak="${h(s.speak)}">🔊 Nghe</button></div>`:''}${s.question?`<div class="quiz"><p class="question">${h(s.question)}</p>${s.options.map(o=>`<button class="option ${lessonChoice===o?'selected':''}" data-choice="${h(o)}">${h(o)}</button>`).join('')}${lessonFeedback?`<p class="feedback ${lessonFeedback.startsWith('Đúng')?'ok':''}">${h(lessonFeedback)}</p>`:''}</div>`:''}</section><div class="lesson-nav"><button class="secondary" data-prev ${i===0?'disabled':''}>‹ Trước</button><button class="primary" data-next ${can?'':'disabled'}>${i===LESSON_STEPS.length-1?'Hoàn thành':'Tiếp tục'} ›</button></div>`}
const rounds=[{prompt:'Buổi sáng, bạn gặp Luc. Bạn nói gì?',expected:['Bonjour']},{prompt:'Luc đưa bạn một tách trà. Bạn nói gì?',expected:['Merci']},{prompt:'Bạn muốn giới thiệu tên của mình.',expected:["Je m'appelle Trân","Je m'appelle Trân."]},{prompt:'Cuộc gặp kết thúc. Bạn nói gì?',expected:['Au revoir']}];
function norm(v){return v.trim().toLocaleLowerCase('fr-FR').replace(/[.!?]+$/g,'')}
function conversation(){const r=rounds[conversationRound];return `${top('Luyện hội thoại')}<section class="card conversation-card"><div class="luc-row">${luc()}<div><strong>Luc</strong><span class="muted">Thực hành có hướng dẫn</span></div></div><p>${h(r.prompt)}</p><div class="hint">Chỉ dùng những gì bạn đã học. Không cần câu dài.</div><input id="conversationInput" placeholder="Viết câu tiếng Pháp…" autocomplete="off"><button class="primary full" data-conversation>Gửi câu trả lời</button>${conversationReply?`<div class="feedback-box">${h(conversationReply)}</div>`:''}</section><section class="card quiet"><span class="glyph">🎧</span><div><strong>Giọng nói — sắp có</strong><p>Ở PWA-2, bạn sẽ có thể nói trực tiếp với Luc bằng micro.</p></div></section>`}
function review(){const learned=ITEMS.filter(i=>state.knownItems.includes(i.id));if(!learned.length)return `${top('Ôn tập')}<section class="empty card"><span class="glyph">↻</span><h2>Chưa có gì để ôn.</h2><p>Hoàn thành vài bước của Bài 1 trước nhé.</p><button class="primary" data-go="lesson">Đi tới Bài 1</button></section>`;const item=learned[reviewIndex%learned.length];return `${top('Ôn tập')}<section class="card flashcard"><span class="pill">Thẻ ${(reviewIndex%learned.length)+1}/${learned.length}</span><p class="prompt">Tiếng Pháp của câu này là gì?</p><h2>${h(item.vi)}</h2>${!reviewRevealed?`<button class="primary full" data-reveal>Hiện đáp án</button>`:`<div class="answer"><span>${h(item.fr)}</span><button class="listen" data-speak="${h(item.fr)}">🔊 Nghe</button></div><p class="muted center">Bạn nhớ từ này thế nào?</p><div class="ratings"><button data-rate="0">Khó</button><button data-rate="1">Được</button><button data-rate="2">Dễ</button></div>`}</section>`}
function progress(){const learned=ITEMS.filter(i=>state.knownItems.includes(i.id));const weak=learned.filter(i=>(state.reviewState[i.id]??1)===0).length;return `${top('Tiến độ')}<section class="progress-hero card"><span class="glyph">👤</span><div><span class="muted">Trân</span><h2>Trình độ A0</h2><p>Bắt đầu từ con số 0 — từng bước nhỏ.</p></div></section><section class="stats"><div class="stat"><span>${state.lesson1Completed?1:0}</span><small>Bài hoàn thành</small></div><div class="stat"><span>${learned.length}</span><small>Đã học</small></div><div class="stat"><span>${weak}</span><small>Cần ôn</small></div></section><section class="card"><h2>Điều đã học</h2>${learned.length?`<div class="learned-list">${learned.map(i=>`<div><strong>${h(i.fr)}</strong><span>${h(i.vi)}</span></div>`).join('')}</div>`:'<p class="muted">Danh sách sẽ xuất hiện khi bạn bắt đầu Bài 1.</p>'}</section><section class="card quiet"><span class="glyph">✦</span><div><strong>Không có điểm XP.</strong><p>Ở đây chỉ theo dõi những gì bạn thực sự hiểu và có thể dùng.</p></div></section>`}
function settings(){return `${top('Cài đặt',{back:true})}<section class="card"><h2>Chẩn đoán</h2><div class="diagnostics"><div><span>Phiên bản</span><strong>v${APP_VERSION} • Build ${BUILD}</strong></div><div><span>Schema</span><strong>${state.schemaVersion}</strong></div><div><span>Trình độ</span><strong>${state.level}</strong></div><div><span>Bài 1</span><strong>${state.lesson1Completed?'Hoàn thành':`Bước ${state.lesson1Step+1}`}</strong></div><div><span>Đã học</span><strong>${state.knownItems.length}</strong></div><div><span>AI adapter</span><strong>mock (offline-safe)</strong></div><div><span>Lần cuối</span><strong>${state.lastActivity?new Date(state.lastActivity).toLocaleString('vi-VN'):'—'}</strong></div></div></section><section class="card danger-zone"><h2>Dữ liệu học</h2><p>Chỉ dùng khi cần bắt đầu lại từ đầu.</p><button class="danger" data-reset>Đặt lại dữ liệu</button></section>`}
function render(){let content=screen==='home'?home():screen==='lesson'?lesson():screen==='conversation'?conversation():screen==='review'?review():screen==='progress'?progress():settings();document.querySelector('#app').innerHTML=shell(content);bind()}
function go(id){screen=id;render();window.scrollTo({top:0,behavior:'smooth'})}
function speak(text){if(!('speechSynthesis'in window))return;window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='fr-FR';u.rate=.78;window.speechSynthesis.speak(u)}
function learn(id){patch(s=>({...s,knownItems:s.knownItems.includes(id)?s.knownItems:[...s.knownItems,id]}))}
function nextLesson(){const i=Math.min(state.lesson1Step,LESSON_STEPS.length-1);if(i===1)learn('bonjour');if(i===3)learn('merci');if(i===5)learn('au-revoir');if(i===6)learn('je-mappelle');if(i===LESSON_STEPS.length-1){patch(s=>({...s,lesson1Completed:true,lesson1Step:i}));go('home');return}lessonChoice=null;lessonFeedback='';patch({lesson1Step:i+1})}
function bind(){document.querySelectorAll('[data-go]').forEach(el=>el.addEventListener('click',()=>go(el.dataset.go)));document.querySelectorAll('[data-speak]').forEach(el=>el.addEventListener('click',()=>speak(el.dataset.speak)));document.querySelectorAll('[data-choice]').forEach(el=>el.addEventListener('click',()=>{const i=state.lesson1Step;const s=LESSON_STEPS[i];lessonChoice=el.dataset.choice;lessonFeedback=lessonChoice===s.answer?'Đúng rồi. Mình tiếp tục nhé.':`Chưa phải. Hãy thử lại — ${s.answer}`;render()}));const prev=document.querySelector('[data-prev]');if(prev)prev.addEventListener('click',()=>{lessonChoice=null;lessonFeedback='';patch({lesson1Step:Math.max(0,state.lesson1Step-1)})});const next=document.querySelector('[data-next]');if(next&&!next.disabled)next.addEventListener('click',nextLesson);const conv=document.querySelector('[data-conversation]');if(conv)conv.addEventListener('click',()=>{const input=document.querySelector('#conversationInput').value;const r=rounds[conversationRound];const ok=r.expected.some(x=>norm(x)===norm(input));conversationReply=ok?'Đúng rồi. Mình tiếp tục nhé.':`Gần đúng. Hãy thử lại với: ${r.expected[0]}`;if(ok){patch(s=>({...s,conversationWins:s.conversationWins+1}));conversationRound=(conversationRound+1)%rounds.length}render()});const reveal=document.querySelector('[data-reveal]');if(reveal)reveal.addEventListener('click',()=>{reviewRevealed=true;render()});document.querySelectorAll('[data-rate]').forEach(el=>el.addEventListener('click',()=>{const learned=ITEMS.filter(i=>state.knownItems.includes(i.id));const item=learned[reviewIndex%learned.length];patch(s=>({...s,reviewState:{...s.reviewState,[item.id]:Number(el.dataset.rate)}}));reviewIndex=(reviewIndex+1)%learned.length;reviewRevealed=false;render()}));const reset=document.querySelector('[data-reset]');if(reset)reset.addEventListener('click',()=>{if(confirm('Xóa toàn bộ tiến độ và bắt đầu lại?')){localStorage.removeItem(KEY);state=initialState();screen='home';render()}})}
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
render();
