(() => {
  'use strict';
  const VERSION='1.6.0', BUILD=11;
  const DEBUG_KEY='tran-french-teacher:debug-fr:v1';
  const LEARNER_KEY='francais-avec-luc:learner:v1';
  const SpeechRecognition=window.SpeechRecognition||window.webkitSpeechRecognition;
  const isDebug=()=>localStorage.getItem(DEBUG_KEY)==='1';
  const isIOS=/iPad|iPhone|iPod/.test(navigator.userAgent)||(navigator.platform==='MacIntel'&&navigator.maxTouchPoints>1);

  const SCENARIOS={
    'bonjour':{vi:'Buổi sáng, bạn gặp một người. Bạn nói gì?',fr:'Le matin, tu rencontres quelqu’un. Que dis-tu ?'},
    'merci':{vi:'Ai đó giúp bạn. Bạn nói gì?',fr:'Quelqu’un t’aide. Que dis-tu ?'},
    'au-revoir':{vi:'Bạn rời đi. Bạn nói gì?',fr:'Tu pars. Que dis-tu ?'},
    'je-mappelle':{vi:'Hãy giới thiệu tên của bạn.',fr:'Présente-toi.'},
    'je-ne-comprends-pas':{vi:'Bạn không hiểu.',fr:'Tu ne comprends pas.'},
    'plus-lentement':{vi:'Người kia nói quá nhanh.',fr:'La personne parle trop vite.'},
    'je-viens-vietnam':{vi:'Nói bạn đến từ Việt Nam.',fr:'Dis que tu viens du Vietnam.'},
    'jhabite-hcm':{vi:'Nói nơi bạn sống.',fr:'Dis où tu habites.'},
    'je-voudrais':{vi:'Bắt đầu một câu gọi món lịch sự.',fr:'Commence une commande polie.'},
    'addition':{vi:'Bạn muốn xin hóa đơn.',fr:'Tu veux demander l’addition.'},
    'combien-ca-coute':{vi:'Bạn muốn hỏi giá.',fr:'Tu veux demander le prix.'},
    'ou-est':{vi:'Bạn muốn hỏi một địa điểm ở đâu.',fr:'Tu veux demander où se trouve un lieu.'},
    'un-billet':{vi:'Bạn muốn mua một vé.',fr:'Tu veux acheter un billet.'},
    'quel-quai':{vi:'Bạn cần biết sân ga nào.',fr:'Tu dois connaître le quai.'},
    'quelle-heure-est-il':{vi:'Bạn muốn biết bây giờ là mấy giờ.',fr:'Tu veux savoir quelle heure il est.'},
    'payer-carte':{vi:'Bạn muốn hỏi có thể trả bằng thẻ không.',fr:'Tu veux demander si tu peux payer par carte.'},
    'table-deux':{vi:'Bạn cần một bàn cho hai người.',fr:'Tu veux une table pour deux.'},
    'jai-mal-ici':{vi:'Bạn đau và muốn chỉ vị trí.',fr:'Tu as mal et tu veux montrer où.'},
    'besoin-medecin':{vi:'Bạn cần bác sĩ.',fr:'Tu as besoin d’un médecin.'},
    'enchantee':{vi:'Bạn gặp một người lần đầu.',fr:'Tu rencontres quelqu’un pour la première fois.'},
    'je-suis-perdue':{vi:'Bạn bị lạc.',fr:'Tu es perdue.'},
    'aidez-moi':{vi:'Bạn cần người khác giúp.',fr:'Tu as besoin d’aide.'}
  };

  let recognition=null,listening=false,transcript='',feedback='',success=false,textMode=false,current=0;
  function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
  function norm(v=''){return String(v).toLocaleLowerCase('fr-FR').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[’']/g,' ').replace(/[…]/g,' ').replace(/[^a-z0-9\s-]/g,' ').replace(/\s+/g,' ').trim()}
  function learner(){try{return JSON.parse(localStorage.getItem(LEARNER_KEY)||'{}')||{}}catch{return{}}}
  function curriculum(){return window.FrenchTranquilleCurriculum||{items:[]}}
  function learnedItems(){const known=new Set(learner().knownItems||[]);return curriculum().items.filter(i=>known.has(i.id))}
  function rounds(){const arr=learnedItems();if(arr.length<=10)return arr;const day=Math.floor(Date.now()/86400000),start=day%arr.length;return Array.from({length:10},(_,i)=>arr[(start+i)%arr.length])}
  function scenarioFor(item){return SCENARIOS[item.id]||{vi:`Hãy nói bằng tiếng Pháp: ${item.vi}`,fr:`Dis en français : ${item.vi}`}}
  function labels(){return isDebug()?{badge:'PWA-2 • 0 €',title:'Entraînement vocal guidé',intro:"Utilise au micro uniquement ce que tu as déjà appris. L'app valide la transcription reconnue, pas la qualité phonétique exacte.",mic:'🎙️ Répondre au micro',listen:'Lucie écoute…',model:'🔊 Écouter le modèle',text:'⌨️ Écrire',hide:'Masquer',validate:'Valider',heard:'Le navigateur a reconnu',ok:'Réponse reconnue. On continue.',retry:'Pas encore reconnue. Réessaie tranquillement.',next:'Continuer ›',none:'Apprends quelques éléments avant de lancer la pratique vocale.',unavailable:'Reconnaissance vocale indisponible dans ce navigateur. Le mode texte reste utilisable.',note:'0 € : aucune API payante. La disponibilité du micro/reconnaissance dépend du navigateur.'}:{badge:'PWA-2 • MIỄN PHÍ',title:'Luyện nói có hướng dẫn',intro:'Chỉ dùng bằng giọng nói những gì bạn đã học. Ứng dụng kiểm tra phần chữ được nhận ra, không chấm phát âm chính xác.',mic:'🎙️ Trả lời bằng giọng nói',listen:'Lucie đang nghe…',model:'🔊 Nghe câu mẫu',text:'⌨️ Viết',hide:'Ẩn',validate:'Kiểm tra',heard:'Trình duyệt nhận được',ok:'Câu trả lời đã được nhận ra. Tiếp tục nhé.',retry:'Chưa nhận ra đúng. Hãy thử lại bình tĩnh.',next:'Tiếp tục ›',none:'Hãy học vài mục trước khi luyện nói.',unavailable:'Nhận dạng giọng nói chưa khả dụng trên trình duyệt này. Bạn vẫn có thể dùng chế độ viết.',note:'0 €: không dùng API trả phí. Khả năng micro/nhận dạng phụ thuộc vào trình duyệt.'}}
  function expectedVariants(item){const base=[item.fr,item.fr.replace(/…/g,'')];if(item.id==='je-mappelle')base.push("Je m'appelle",'Je m appelle tran','Je m appelle');if(item.id==='eau')base.push('de l eau','eau');if(item.id==='cafe')base.push('cafe');if(item.id==='the')base.push('the');if(item.id==='addition')base.push('l addition');if(item.id==='euros')base.push('euro','euros');return [...new Set(base.map(norm).filter(Boolean))]}
  function accepted(item,value){const got=norm(value);if(!got)return false;return expectedVariants(item).some(v=>got===v||got.includes(v)||(v.length>5&&v.includes(got)&&got.length>=4))}
  function speak(item){if(!('speechSynthesis'in window))return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(item.fr.replace('…',''));u.lang='fr-FR';speechSynthesis.speak(u)}
  function evaluate(value){const rs=rounds(),item=rs[current%Math.max(rs.length,1)],l=labels();if(!item)return;transcript=value;success=accepted(item,value);feedback=success?l.ok:`${l.retry} → ${item.fr}`;renderCard()}
  function startRecognition(){if(!SpeechRecognition||listening)return;const l=labels();recognition=new SpeechRecognition();recognition.lang='fr-FR';recognition.continuous=false;recognition.interimResults=false;recognition.maxAlternatives=5;recognition.onstart=()=>{listening=true;transcript='';feedback='';success=false;renderCard()};recognition.onresult=e=>{const result=e.results[0],candidates=[];for(let i=0;i<result.length;i++)candidates.push(result[i].transcript||'');const item=rounds()[current%Math.max(rounds().length,1)];const best=candidates.find(x=>accepted(item,x))||candidates[0]||'';evaluate(best)};recognition.onerror=()=>{feedback=l.unavailable;renderCard()};recognition.onend=()=>{listening=false;renderCard()};try{recognition.start()}catch{feedback=l.unavailable;renderCard()}}
  function next(){current=(current+1)%Math.max(rounds().length,1);transcript='';feedback='';success=false;textMode=false;renderCard()}
  function injectStyles(){if(document.getElementById('free-voice-style'))return;const s=document.createElement('style');s.id='free-voice-style';s.textContent=`.free-voice-card{border-color:rgba(70,190,130,.28)!important}.free-voice-head{display:flex;justify-content:space-between;align-items:flex-start;gap:12px}.free-voice-badge{display:inline-flex;padding:5px 9px;border-radius:999px;border:1px solid rgba(85,190,135,.35);background:rgba(35,110,75,.18);color:#a9ddbf;font-size:.7rem;font-weight:800}.free-voice-prompt{margin:14px 0;padding:15px;border-radius:14px;background:#0c1726;border:1px solid #263b53;color:#e8eef5;line-height:1.5}.free-voice-actions{display:grid;grid-template-columns:1fr 1fr;gap:9px}.free-voice-actions button{min-height:50px;border-radius:14px;border:1px solid #344b66;background:#13243a;color:#eaf1f8;font-weight:800;cursor:pointer}.free-voice-actions .free-mic{grid-column:1/-1;background:#f4efe6;color:#0a1422;border:0;min-height:56px}.free-voice-result,.free-voice-feedback{margin-top:12px;padding:12px 13px;border-radius:12px;background:#0d1929}.free-voice-feedback{color:#d5c58c}.free-voice-feedback.ok{color:#a8d9be}.free-voice-note{font-size:.74rem!important;color:#71869f!important;margin-top:12px!important}.free-next{width:100%;margin-top:10px;min-height:48px;border:0;border-radius:13px;background:#e8e0d2;color:#0b1421;font-weight:800;cursor:pointer}.free-voice-textbox{display:grid;grid-template-columns:1fr auto;gap:8px;margin-top:10px}.free-voice-textbox input{min-width:0;min-height:48px;border-radius:12px;border:1px solid #354961;background:#0d1929;color:#eef4fb;padding:0 12px;font-size:16px}.free-voice-textbox button{min-width:84px;border-radius:12px;border:1px solid #3b526f;background:#17283d;color:#eef4fb;font-weight:800}`;document.head.appendChild(s)}
  function renderCard(){const card=document.getElementById('free-voice-card');if(!card)return;const l=labels(),rs=rounds();if(!rs.length){card.innerHTML=`<span class="free-voice-badge">${l.badge}</span><h2>${l.title}</h2><p>${l.none}</p><p class="free-voice-note">${l.note}</p>`;return}const item=rs[current%rs.length],scenario=scenarioFor(item),prompt=isDebug()?scenario.fr:scenario.vi;card.innerHTML=`<div class="free-voice-head"><div><span class="free-voice-badge">${l.badge}</span><h2>${l.title}</h2></div><span>🎙️</span></div><p>${l.intro}</p><div class="free-voice-prompt">${esc(prompt)}<br><small>${current%rs.length+1}/${rs.length}</small></div><div class="free-voice-actions"><button class="free-mic" id="free-voice-mic" ${!SpeechRecognition||listening?'disabled':''}>${listening?l.listen:l.mic}</button><button id="free-voice-model">${l.model}</button><button id="free-voice-text">${textMode?l.hide:l.text}</button></div>${textMode?`<div class="free-voice-textbox"><input id="free-voice-text-input" placeholder="${esc(item.fr)}"><button id="free-voice-validate">${l.validate}</button></div>`:''}${!SpeechRecognition?`<div class="free-voice-feedback">${l.unavailable}</div>`:''}${transcript?`<div class="free-voice-result"><small>${l.heard}</small><br><strong>${esc(transcript)}</strong></div>`:''}${feedback?`<div class="free-voice-feedback ${success?'ok':''}">${esc(feedback)}</div>`:''}${success?`<button class="free-next" id="free-voice-next">${l.next}</button>`:''}<p class="free-voice-note">${l.note} ${isIOS?'iPhone / iOS':''}</p>`;card.querySelector('#free-voice-mic')?.addEventListener('click',startRecognition);card.querySelector('#free-voice-model')?.addEventListener('click',()=>speak(item));card.querySelector('#free-voice-text')?.addEventListener('click',()=>{textMode=!textMode;renderCard()});card.querySelector('#free-voice-validate')?.addEventListener('click',()=>evaluate(card.querySelector('#free-voice-text-input')?.value||''));card.querySelector('#free-voice-next')?.addEventListener('click',next)}
  function injectCard(){const conversation=document.querySelector('.conversation-card');if(!conversation||document.getElementById('free-voice-card'))return;const card=document.createElement('section');card.id='free-voice-card';card.className='card free-voice-card';conversation.before(card);renderCard()}
  function refresh(){injectStyles();injectCard()}
  let scheduled=false;const observer=new MutationObserver(()=>{if(scheduled)return;scheduled=true;requestAnimationFrame(()=>{scheduled=false;refresh()})});
  const start=()=>{refresh();observer.observe(document.documentElement,{subtree:true,childList:true})};
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
  window.FrenchTranquilleFreeVoice={version:VERSION,build:BUILD,isIOS,available:Boolean(SpeechRecognition)};
})();