(() => {
  'use strict';
  const VERSION='1.5.0', BUILD=10;
  const VOICE_KEY='tran-french-teacher:luc-voice:v1';
  const DEBUG_KEY='tran-french-teacher:debug-fr:v1';
  const RATE_KEY='tran-french-teacher:luc-rate:v1';
  const PITCH_KEY='tran-french-teacher:luc-pitch:v1';
  const isDebug=()=>localStorage.getItem(DEBUG_KEY)==='1';
  const isIOS=/iPad|iPhone|iPod/.test(navigator.userAgent)||(navigator.platform==='MacIntel'&&navigator.maxTouchPoints>1);
  if(!('speechSynthesis'in window)||!('SpeechSynthesisUtterance'in window))return;
  const synth=window.speechSynthesis,nativeSpeak=synth.speak.bind(synth);
  const femaleHints=['amelie','amélie','audrey','aurelie','aurélie','marie','celine','céline','virginie','lea','léa','alice','google français','google french'];
  function frenchVoices(){return synth.getVoices().filter(v=>/^fr(?:-|$)/i.test(v.lang||''))}
  function score(v){const lang=(v.lang||'').toLowerCase(),name=(v.name||'').toLowerCase();let s=0;if(lang==='fr-fr')s+=100;else if(lang.startsWith('fr-'))s+=70;else if(lang==='fr')s+=60;if(/google.*fran|google.*french/.test(name))s+=65;if(/premium|enhanced|amélior|amelior|natural|neural/.test(name))s+=40;if(femaleHints.some(x=>name.includes(x)))s+=22;if(isIOS&&v.localService)s+=18;return s}
  function autoVoice(){return [...frenchVoices()].sort((a,b)=>score(b)-score(a))[0]||null}
  function selectedVoice(){const stored=localStorage.getItem(VOICE_KEY),voices=frenchVoices();if(stored&&stored!=='auto'){const exact=voices.find(v=>v.voiceURI===stored||v.name===stored);if(exact)return exact}return autoVoice()}
  function currentRate(){const n=Number(localStorage.getItem(RATE_KEY));return Number.isFinite(n)&&n>=.65&&n<=1.2?n:.84}
  function currentPitch(){const n=Number(localStorage.getItem(PITCH_KEY));return Number.isFinite(n)&&n>=.7&&n<=1.3?n:1.04}
  synth.speak=utterance=>{try{if(utterance&&/^fr(?:-|$)/i.test(utterance.lang||'fr-FR')){const voice=selectedVoice();if(voice)utterance.voice=voice;utterance.lang=voice?.lang||'fr-FR';utterance.rate=currentRate();utterance.pitch=currentPitch()}}catch{}return nativeSpeak(utterance)};
  function preview(){synth.cancel();const u=new SpeechSynthesisUtterance("Bonjour Trân. Je m'appelle Lucie. On va apprendre le français ensemble.");u.lang='fr-FR';synth.speak(u)}
  function injectStyles(){if(document.getElementById('lucie-voice-style'))return;const s=document.createElement('style');s.id='lucie-voice-style';s.textContent=`.lucie-voice-card{border-color:rgba(88,166,255,.3)!important}.lucie-voice-card select,.lucie-voice-card input[type=range]{width:100%}.lucie-voice-card select{min-height:46px;margin:10px 0 12px;padding:0 12px;border-radius:12px;border:1px solid #354961;background:#0d1929;color:#eef4fb}.lucie-voice-card .voice-meta{display:grid;gap:6px;margin:10px 0 14px;font-size:.82rem;color:#91a4bc}.lucie-voice-card .voice-actions{display:grid;grid-template-columns:1fr 1fr;gap:8px}.lucie-voice-card button{min-height:46px;border:1px solid #3a5270;border-radius:12px;background:#14253a;color:#e9f1f9;font-weight:700;cursor:pointer}.lucie-voice-card label{display:grid;gap:6px;margin:12px 0;color:#a8b8cb;font-size:.8rem}.lucie-voice-card output{color:#f4efe6;font-weight:700}`;document.head.appendChild(s)}
  function label(v){return `${v.name} — ${v.lang} — ${v.localService?'local':'réseau'}`}
  function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
  function injectCard(){if(!isDebug())return;const main=document.querySelector('.content');if(!main||document.getElementById('lucie-voice-card'))return;const heading=[...main.querySelectorAll('h2')].find(h=>h.textContent.trim()==='Diagnostic');if(!heading)return;const voices=frenchVoices(),stored=localStorage.getItem(VOICE_KEY)||'auto',chosen=selectedVoice();const card=document.createElement('section');card.id='lucie-voice-card';card.className='card lucie-voice-card';card.innerHTML=`<span class="pill">AUDIO DEBUG</span><h2>🎙️ Voix de Lucie — ${isIOS?'iPhone / iOS':'navigateur actuel'}</h2><p>Choisis la meilleure voix française réellement disponible sur cet appareil. Le choix reste local.</p><div class="voice-meta"><span>Plateforme : <strong>${isIOS?'iOS / iPhone':esc(navigator.platform||'autre')}</strong></span><span>Voix françaises : <strong>${voices.length}</strong></span><span>Voix actuelle : <strong>${esc(chosen?.name||'voix système')}</strong></span></div><select id="lucie-voice-select"><option value="auto">Auto — meilleure voix française disponible</option>${voices.map(v=>`<option value="${esc(v.voiceURI||v.name)}" ${stored===(v.voiceURI||v.name)?'selected':''}>${esc(label(v))}</option>`).join('')}</select><label>Vitesse : <output id="lucie-rate-out">${currentRate().toFixed(2)}</output><input id="lucie-rate" type="range" min="0.70" max="1.05" step="0.02" value="${currentRate()}"></label><label>Hauteur : <output id="lucie-pitch-out">${currentPitch().toFixed(2)}</output><input id="lucie-pitch" type="range" min="0.85" max="1.10" step="0.01" value="${currentPitch()}"></label><div class="voice-actions"><button id="lucie-voice-test">▶ Tester Lucie</button><button id="lucie-voice-auto">↺ Auto</button></div>`;const debug=document.getElementById('debug-fr-card');if(debug)debug.after(card);else heading.closest('.card').before(card);card.querySelector('#lucie-voice-select').addEventListener('change',e=>{localStorage.setItem(VOICE_KEY,e.target.value);preview();card.remove();setTimeout(injectCard,60)});const rate=card.querySelector('#lucie-rate'),pitch=card.querySelector('#lucie-pitch');rate.addEventListener('input',()=>{localStorage.setItem(RATE_KEY,rate.value);card.querySelector('#lucie-rate-out').value=Number(rate.value).toFixed(2)});pitch.addEventListener('input',()=>{localStorage.setItem(PITCH_KEY,pitch.value);card.querySelector('#lucie-pitch-out').value=Number(pitch.value).toFixed(2)});card.querySelector('#lucie-voice-test').addEventListener('click',preview);card.querySelector('#lucie-voice-auto').addEventListener('click',()=>{localStorage.setItem(VOICE_KEY,'auto');localStorage.removeItem(RATE_KEY);localStorage.removeItem(PITCH_KEY);card.remove();injectCard();preview()})}
  function refresh(){injectStyles();injectCard()}
  let scheduled=false;const observer=new MutationObserver(()=>{if(scheduled)return;scheduled=true;requestAnimationFrame(()=>{scheduled=false;refresh()})});
  const start=()=>{refresh();observer.observe(document.documentElement,{subtree:true,childList:true});synth.addEventListener?.('voiceschanged',()=>{document.getElementById('lucie-voice-card')?.remove();refresh()});synth.getVoices()};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
  window.LucieVoice={list:frenchVoices,current:selectedVoice,preview,isIOS,version:VERSION,build:BUILD};window.LucVoice=window.LucieVoice;
})();
